services:
  php:
    build: ./
    container_name: fsms-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fsms-mysql
    environment:
      MYSQL_DATABASE: fsms
      MYSQL_USER: fsms
      MYSQL_PASSWORD: fsms123
      MYSQL_ROOT_PASSWORD: root123
      TZ: UTC
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: fsms-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  mysql_data:
